FROM jenkins/jenkins:lts

RUN wget -O - http://packages.couchbase.com/ubuntu/cou
        && apt-get update \
        && apt-get install -y \

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml


RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt


