FROM jenkins/jenkins:lts

RUN apt-get update 
    && 

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml


RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt


