jenkins:
  systemMessage: "AutomatingGuy demo: configured automatically with JCasC plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:8080/
credentials:
  system:
    domainCredentials:
      credentials:
        - certificate:
            scope: SYSTEM
            id: ssh_private_key
            keyStoreSource:
              fileOnMaster:
                keyStoreFile: /docker/secret/id_rsa      
  nodes:
    - permanent:
        name: "agent-demo"
        remoteFS: "/home/jenkins"
        launcher:
          jnlp:

  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp2"
tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git
credentials:
  system:
    domainCredentials:
      credentials:
        - certificate:
            scope: SYSTEM
            id: ssh_private_key
            keyStoreSource:
              fileOnMaster:
                keyStoreFile: /docker/secret/id_rsa
jobs:
  - script: >
      job('demo') {
        steps {
          shell('echo Hello World!')
        }
      }
  - script: >
      pipelineJob('pipeline-demo') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@github.com:nexmoinc/k8s-apps.git')
                  credentials('github-ssh-keys')
                }
                branches('master')
                scriptPath('/Jenkinsfile')
              }
            }
          }
        }
      }               